<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="blog.xsl" type="text/xsl"?>
<!DOCTYPE posts [
	<!ELEMENT posts (post+)>
	<!ELEMENT post  (date,title,desc,slug)>
	<!ELEMENT date  (#PCDATA)>
	<!ELEMENT title (#PCDATA)>
	<!ELEMENT desc  (#PCDATA)>
	<!ELEMENT slug  (#PCDATA)>
]>
<posts>
	<post>
		<date></date>
		<title>Benchmarking WebAssembly</title>
		<desc>Is WebAssembly faster than JavaScript? It depends...</desc>
		<slug>/bench-wasm.xml</slug>
	</post>
	<post>
		<date></date>
		<title>Your tests don't need to be .PHONY</title>
		<desc>How to improve your Makefile by removing .PHONY tests.</desc>
		<slug>/make-phony.xml</slug>
	</post>
	<post>
		<date>Feb 20, 2020</date>
		<title>XSLT: Client-side templating without JavaScript</title>
		<desc>The lost art of eXtensible Stylesheet Language Transformations.</desc>
		<slug>/xslt-templating.xml</slug>
	</post>
</posts>
